### ISSUE TITLE
The example code will be a zombie process

### ISSUE THREAD

**Issue by MaHuanAAA** [AI4LIFE-GROUP/SpLiCE#1]
I tried ```python decompose_image.py -path 000000308175.jpg -out_path image308175_decomp.txt -l1_penalty 0.25 --verbose```, and it downloaded all needed caches. However, there is nothing for output, and NVIDA Memory-Usage is zero with the process seems still running.

**Comment by alex-oesterling** [comment]
Hey! So after testing it appears as though we have left the default device to be "cpu" in the `decompose_image.py` arguments. You may want to check that you are actually running on `cuda`.

**Comment by MaHuanAAA** [comment]
Thanks for your response.    I did use Cuda, but it keeps state of loading the model. I replaced open_clip with ckpoints released by openai and it works. Perhaps due to differences in the environment.

**Comment by alex-oesterling** [comment]
So you resolved the issue by using clip instead of open_clip? Thanks for responding with your solution :)

**Comment by MaHuanAAA** [comment]
There is a typo in the equation in Property 3.2., I guess.
