### ISSUE TITLE
Will more models be supported?

### ISSUE THREAD

**Issue by yinghuozijin** [AI4LIFE-GROUP/SpLiCE#5]
Thanks for your cool work!
Do you plan to support more models, e.g., ViT-L/14? Or how could we get the corresponding concept dictionary by ourselves?
Thanks a lot!

**Comment by alex-oesterling** [comment]
Hi! Please check splice.py, lines 115-129 for an example of how to construct the concept dictionary. SpLiCE itself can handle any VLM (see models.py) but you will need to precompute the dictionary using the above lines.
